from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class CurrentVector(BaseModel):
    latitude: float = Field(..., description="Latitude coordinate")
    longitude: float = Field(..., description="Longitude coordinate")
    u_component: float = Field(..., description="Zonal current velocity component (m/s or knots)")
    v_component: float = Field(..., description="Meridional current velocity component (m/s or knots)")
    velocity_knots: float = Field(..., description="Magnitude speed in knots")
    direction: str = Field(..., description="Cardinal heading direction")


class OceanState(BaseModel):
    """
    Standard scientific state object generated by the Ocean Intelligence Engine.
    Serves as the common data contract across simulation engines, dataset loaders,
    and API layers.
    """
    region: str = Field(..., description="Target geographic ocean region name")
    forecast_time: str = Field(..., description="ISO 8601 timestamp for the forecast state")
    current_vectors: List[CurrentVector] = Field(default_factory=list, description="Surface velocity vectors")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Dataset metadata, bounding boxes, & parameters")
    source: str = Field("CMEMS Copernicus Marine Service", description="Data provider or simulation engine source identifier")
    confidence: float = Field(0.93, description="Model or dataset confidence coefficient (0.0 - 1.0)")

    # Extensible fields for future module integration
    temperature: Optional[float] = Field(None, description="Sea surface temperature (°C)")
    salinity: Optional[float] = Field(None, description="Salinity PSU")
    chlorophyll: Optional[float] = Field(None, description="Chlorophyll-a concentration mg/m3")
    wave_height: Optional[float] = Field(None, description="Significant wave height meters")
    winds: Optional[Dict[str, Any]] = Field(None, description="Surface wind vector field")
    particle_simulation: Optional[Dict[str, Any]] = Field(None, description="Lagrangian particle state")
    hotspots: Optional[List[Dict[str, Any]]] = Field(None, description="Plastic accumulation hotspots")

    model_config = {
        "json_schema_extra": {
            "example": {
                "region": "Bay of Bengal",
                "forecast_time": "2026-07-25T12:00:00Z",
                "current_vectors": [
                    {
                        "latitude": 15.0,
                        "longitude": 88.0,
                        "u_component": 0.42,
                        "v_component": 0.18,
                        "velocity_knots": 2.4,
                        "direction": "North-East"
                    }
                ],
                "metadata": {
                    "grid_resolution": "0.083 deg",
                    "dataset_id": "GLOBAL_ANALYSISFORECAST_PHY_001_024",
                    "bounding_box": [10.0, 80.0, 22.0, 95.0]
                },
                "source": "CMEMS Copernicus Marine Service",
                "confidence": 0.93
            }
        }
    }
